name: Create and Commit SBOM (signed)

on:
  pull_request:
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"
      - "sbom/**"

permissions:
  id-token: write         # wymagane przez Gitsign do OIDC (keyless signing)
  contents: write         # wymagane do commitowania/pushowania
  pull-requests: write    # opcjonalnie, jeśli chcesz modyfikować PR

jobs:
  sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry --output-format JSON --output-file ../sbom/hello-world.sbom

      - name: Setup Gitsign for keyless commit signing
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit and push signed SBOM to PR branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sbom/hello-world.sbom
          git commit -S -m "chore: add signed SBOM"
          git push
