name: Generate and Commit Signed SBOM with PR

on:
  pull_request:
    types: [opened, reopened] 
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Checkout PR branch (base for the PR we will open)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry --output-format JSON --output-file ../sbom/hello-world.sbom

      - name: Create or update Pull Request with SBOM (signed commit)
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "sbom/update-${{ github.head_ref }}"
          base: ${{ github.head_ref }}
          add-paths: |
            sbom/hello-world.sbom
          commit-message: "chore: add signed SBOM"
          title: "chore: add signed SBOM"
          body: "This PR adds or updates the signed SBOM file."
          sign-commits: true
