name: Generate and Commit Signed SBOM

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"

permissions:
  contents: write
  pull-requests: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    # Restrict to PRs from the same repository
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry \
            --output-format JSON \
            --output-file ../sbom/hello-world.json
            
      - name: Commit SBOM to PR branch (Verified via API, fixed filename)
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        env:
          FILE_PATH: sbom/hello-world.json
        with:
          script: |
            const fs = require('fs');
            const path = process.env.FILE_PATH;

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = context.payload.pull_request.head.ref;

            // Read the generated SBOM file and encode it to base64
            const content = fs.readFileSync(path, { encoding: 'base64' });

            // Try to get the existing file SHA (required if the file already exists)
            let sha = undefined;
            try {
              const { data } = await github.rest.repos.getContent({
                owner, repo, path, ref: branch
              });
              if (!Array.isArray(data) && data && data.sha) {
                sha = data.sha;
              }
            } catch (e) {
              // If the file does not exist yet (404), it's fine — create will work without sha
              if (e.status !== 404) throw e; // rethrow other errors
            }

            // Create or update the file on the PR branch
            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path,
              branch,
              message: 'chore(sbom): update hello-world SBOM',
              content,
              ...(sha ? { sha } : {}) // include sha only if updating existing file
            });
