name: Generate and Commit Signed SBOM with PR

on:
  pull_request:
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"
      - "sbom/**"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry --output-format JSON --output-file ../sbom/hello-world.sbom

      - name: Setup Gitsign for keyless commit signing
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit SBOM file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sbom/hello-world.sbom
          git commit -S -m "chore: add signed SBOM" || echo "No changes to commit"

      - name: Create or update Pull Request with SBOM
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore: add signed SBOM
          title: "chore: add signed SBOM"
          body: "This PR adds or updates the signed SBOM file."
          branch: "sbom/update-${{ github.head_ref }}"
          base: ${{ github.head_ref }}
          merge-method: squash
