name: Commit SBOM to PR Branch

on:
  pull_request:
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"
      - "sbom/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-sbom:
    runs-on: ubuntu-latest
    # Only run if the PR is from the same repo, not a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry --output-format JSON --output-file ../sbom/hello-world.sbom

      - name: Commit SBOM file to PR branch using GitHub REST API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: sbom/hello-world.sbom
          DESTINATION_BRANCH: ${{ github.head_ref }}
        run: |
          CONTENT=$(base64 -w0 $FILE_TO_COMMIT)
          MESSAGE="chore: add SBOM file"
          # Get SHA if file already exists
          SHA=$(gh api repos/${{ github.repository }}/contents/$FILE_TO_COMMIT?ref=$DESTINATION_BRANCH --jq .sha || echo "")
          PAYLOAD="{\"message\":\"$MESSAGE\",\"content\":\"$CONTENT\",\"branch\":\"$DESTINATION_BRANCH\""
          if [ -n "$SHA" ]; then
            PAYLOAD="$PAYLOAD, \"sha\":\"$SHA\""
          fi
          PAYLOAD="$PAYLOAD}"
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/contents/$FILE_TO_COMMIT \
            --input <(echo $PAYLOAD)
