name: Generate and Commit Signed SBOM

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "hello-world/pyproject.toml"
      - "hello-world/poetry.lock"

permissions:
  contents: write
  pull-requests: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    # Restrict to PRs from the same repository
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install CycloneDX 7.x
        run: |
          python -m pip install --upgrade pip
          pip install "cyclonedx-bom==7.*"

      - name: Generate SBOM (CycloneDX JSON from Poetry project)
        working-directory: ./hello-world
        run: |
          mkdir -p ../sbom
          cyclonedx-py poetry \
            --output-format JSON \
            --output-file ../sbom/hello-world.json
            
      - name: Commit SBOM to PR branch 
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          FILE_PATH: sbom/hello-world.json
        with:
          script: |
            const fs = require('fs');
            const path = process.env.FILE_PATH;

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = context.payload.pull_request.head.ref;

            // Read file and base64-encode for API
            const content = fs.readFileSync(path, { encoding: 'base64' });

            // Try to get existing file SHA (needed only for updates)
            let sha;
            try {
              const { data } = await github.rest.repos.getContent({
                owner, repo, path, ref: branch
              });
              if (!Array.isArray(data)) sha = data.sha;
            } catch (e) {
              // Probably a 404: file doesn't exist yet on this branch — that's fine.
            }

            // Create or update the file on the PR head branch
            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path,
              message: 'chore(sbom): update hello-world SBOM',
              content,
              branch,
              sha
            });

